# Smart Dependabot configuration for puppet-thanos
# Automatically detected: github-actions

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: 09:00
      timezone: America/New_York
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
      include: scope
    labels:
      - dependencies
      - priority-high
